import type { Metadata } from "next";
import { Montserrat, Source_Sans_3, Fira_Code } from "next/font/google";
import "./globals.css";

// Brand fonts
const heading = Montserrat({ subsets: ["latin"], variable: "--font-heading" });
const body = Source_Sans_3({ subsets: ["latin"], variable: "--font-body" });
const code = Fira_Code({ subsets: ["latin"], variable: "--font-code" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${heading.variable} ${body.variable} ${code.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
